version: '2'
services:
  rcm_blogging_backend:
    container_name: web_rcm_blogging_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "52001:52001"
  rcm_blogging_frontend:
    build: ./admin-panel
    container_name: rcm_blogging_frontend
    ports:
      - "52002:80"
    restart: always